// <auto-generated />
using CallAppUserManagementTask.cs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CallAppUserManagementTask.cs.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231130193930_fourth")]
    partial class fourth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CallAppUserManagementTask.cs.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            email = "Sincere@april.biz",
                            isActive = true,
                            password = "Password1!",
                            username = "Bret"
                        },
                        new
                        {
                            id = 2,
                            email = "Shanna@melissa.tv",
                            isActive = true,
                            password = "Password1!",
                            username = "Antonette"
                        },
                        new
                        {
                            id = 3,
                            email = "Nathan@yesenia.net",
                            isActive = true,
                            password = "Password1!",
                            username = "Samantha"
                        },
                        new
                        {
                            id = 4,
                            email = "Julianne.OConner@kory.org",
                            isActive = true,
                            password = "Password1!",
                            username = "Karianne"
                        },
                        new
                        {
                            id = 5,
                            email = "Lucio_Hettinger@annie.ca",
                            isActive = false,
                            password = "Password1!",
                            username = "Kamren"
                        });
                });

            modelBuilder.Entity("CallAppUserManagementTask.cs.Models.UserProfile", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("personalNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("userid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("userid")
                        .IsUnique();

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            id = 1,
                            firstName = "Leanne",
                            lastName = "Graham",
                            personalNumber = "55359788670",
                            userid = 1
                        },
                        new
                        {
                            id = 2,
                            firstName = "Ervin",
                            lastName = "Howell",
                            personalNumber = "24017436263",
                            userid = 2
                        },
                        new
                        {
                            id = 3,
                            firstName = "Clementine",
                            lastName = "Bauch",
                            personalNumber = "59866202820",
                            userid = 3
                        },
                        new
                        {
                            id = 4,
                            firstName = "Patricia",
                            lastName = "Lebsack",
                            personalNumber = "22418390819",
                            userid = 4
                        },
                        new
                        {
                            id = 5,
                            firstName = "Chelsey",
                            lastName = "Dietrich",
                            personalNumber = "80023584477",
                            userid = 5
                        });
                });

            modelBuilder.Entity("CallAppUserManagementTask.cs.Models.UserProfile", b =>
                {
                    b.HasOne("CallAppUserManagementTask.cs.Models.User", "user")
                        .WithOne("userProfile")
                        .HasForeignKey("CallAppUserManagementTask.cs.Models.UserProfile", "userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("CallAppUserManagementTask.cs.Models.User", b =>
                {
                    b.Navigation("userProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
